# GitHub Sponsors (1 org OR up to 4 users)
github: [huzaifa1-0]

# External funding platforms (ONLY one username per platform)
patreon: huzaifarashid
ko_fi: huzaifa
liberapay: huzaifarashid
open_collective: orhanix
issuehunt: huzaifa
polar: huzaifa
buy_me_a_coffee: huzaifa
thanks_dev: u/gh/huzaifa-rashid

# Custom funding URLs (up to 4)
custom:
  - "https://paypal.me/huzaifarashid"
  - "https://orhanix.com/support"
