# These are supported funding model platforms

github: [huzaifa1-0]        # GitHub Sponsors username (up to 4)
patreon: huzaifarashid          # Patreon username
open_collective: orhanix        # Open Collective project name
ko_fi: huzaifa                  # Ko-fi username
liberapay: huzaifarashid        # Liberapay username
issuehunt: huzaifa              # IssueHunt username
polar: huzaifa                  # Polar username
buy_me_a_coffee: huzaifa        # Buy Me a Coffee username
thanks_dev: huzaifa             # thanks.dev username

