# Use the official Nginx image to serve static content
FROM nginx:alpine

# Copy the contents of the current directory (the frontend folder)
# to the Nginx public directory
COPY . /usr/share/nginx/html/