# Start with a Python 3.12 image
FROM python:3.12-slim

# Set the working directory
WORKDIR /code

# Copy the requirements file to the root of the workdir
COPY ./requirements.txt /code/requirements.txt

# Install the Python dependencies
RUN pip install --no-cache-dir -r /code/requirements.txt

# Copy the backend application code
COPY ./backend /code/backend


# Set the PYTHONPATH to include both the root /code directory and the backend directory
ENV PYTHONPATH="/code:/code/backend"

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]