blank_issues_enabled: false
contact_links:
  - name: General questions
    url: https://github.com/huzaifa1-0/eMCP-Nexus/discussions
    about: Please use GitHub Discussions for support and open-ended questions.
